language: php
 
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm # on Trusty only
    - nightly
 
before_script:
  - composer install --dev

after_script:
  env:
    CODECLIMATE_REPO_TOKEN:CODECLIMATE_TT