<?php
/**
 * Created by PhpStorm.
 * User: Rida Amirini
 * Date: 27.08.2017
 * Time: 00:23
 */

use PHPUnit\Framework\TestCase;

class SampleTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testOne()
    {
        $this->assertTrue(true);
    }
}
